name = "zufallstour-3000"
main = "src/worker.js"
compatibility_date = "2024-05-01"

assets = { directory = "dist", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "zufallstour-3000"
database_id = "227a9d95-f3e1-48b2-bcf5-6a4a4e91f27d"

[observability.logs]
enabled = true
