name = "zufallstour-3000"
main = "src/worker.js"
compatibility_date = "2024-05-01"

[build]
command = "npm run build"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "DB"
id = ""
preview_id = ""
