const SEED_STATIONS = [
  { name: "Adenauerplatz", types:["U"], lines:["U7"] },
  { name: "Adlershof", types:["S"], lines:["S45","S46","S8","S85","S9"] },
  { name: "Afrikanische Straße", types:["U"], lines:["U6"] },
  { name: "Ahrensfelde", types:["S"], lines:["S7"] },
  { name: "Albrechtshof", types:["R"], lines:[] },
  { name: "Alexanderplatz", types:["S","U","R"], lines:["S3","S5","S7","S9","U2","U5","U8"] },
  { name: "Altglienicke", types:["S"], lines:["S45","S9"] },
  { name: "Alt-Mariendorf", types:["U"], lines:["U6"] },
  { name: "Alt-Reinickendorf", types:["S"], lines:["S25"] },
  { name: "Altstadt Spandau", types:["U"], lines:["U7"] },
  { name: "Alt-Tegel", types:["U"], lines:["U6"] },
  { name: "Alt-Tempelhof", types:["U"], lines:["U6"] },
  { name: "Amrumer Straße", types:["U"], lines:["U9"] },
  { name: "Anhalter Bahnhof", types:["S"], lines:["S1","S2","S25","S26"] },
  { name: "Attilastraße", types:["S"], lines:["S2"] },
  { name: "Augsburger Straße", types:["U"], lines:["U3"] },
  { name: "Baumschulenweg", types:["S"], lines:["S45","S46","S47","S8","S85","S9"] },
  { name: "Bayerischer Platz", types:["U"], lines:["U4","U7"] },
  { name: "Bellevue", types:["S"], lines:["S3","S5","S7","S9"] },
  { name: "Berliner Straße", types:["U"], lines:["U7","U9"] },
  { name: "Bernauer Straße", types:["U"], lines:["U8"] },
  { name: "Betriebsbahnhof Rummelsburg", types:["S"], lines:["S3"] },
  { name: "Beusselstraße", types:["S"], lines:["S41","S42"] },
  { name: "Biesdorf", types:["S"], lines:["S5"] },
  { name: "Biesdorf-Süd", types:["U"], lines:["U5"] },
  { name: "Birkenstraße", types:["U"], lines:["U9"] },
  { name: "Bismarckstraße", types:["U"], lines:["U2","U7"] },
  { name: "Blankenburg", types:["S"], lines:["S2","S8","S26"] },
  { name: "Blaschkoallee", types:["U"], lines:["U7"] },
  { name: "Blissestraße", types:["U"], lines:["U7"] },
  { name: "Boddinstraße", types:["U"], lines:["U8"] },
  { name: "Bornholmer Straße", types:["S"], lines:["S1","S2","S25","S26","S8","S85"] },
  { name: "Borsigwerke", types:["U"], lines:["U6"] },
  { name: "Botanischer Garten", types:["S"], lines:["S1"] },
  { name: "Brandenburger Tor", types:["S","U"], lines:["S1","S2","S25","S26","U5"] },
  { name: "Breitenbachplatz", types:["U"], lines:["U3"] },
  { name: "Britz-Süd", types:["U"], lines:["U7"] },
  { name: "Buch", types:["S"], lines:["S2"] },
  { name: "Buckower Chaussee", types:["S"], lines:["S2"] },
  { name: "Bülowstraße", types:["U"], lines:["U2"] },
  { name: "Bundesplatz", types:["S","U"], lines:["S41","S42","S46","U9"] },
  { name: "Bundestag", types:["U"], lines:["U5"] },
  { name: "Charlottenburg", types:["S","R"], lines:["S3","S5","S7","S9"] },
  { name: "Cottbusser Platz", types:["U"], lines:["U5"] },
  { name: "Dahlem-Dorf", types:["U"], lines:["U3"] },
  { name: "Deutsche Oper", types:["U"], lines:["U2"] },
  { name: "Eberswalder Straße", types:["U"], lines:["U2"] },
  { name: "Eichborndamm", types:["S"], lines:["S25"] },
  { name: "Eisenacher Straße", types:["U"], lines:["U7"] },
  { name: "Elsterwerdaer Platz", types:["U"], lines:["U5"] },
  { name: "Ernst-Reuter-Platz", types:["U"], lines:["U2"] },
  { name: "Fehrbelliner Platz", types:["U"], lines:["U3","U7"] },
  { name: "Feuerbachstraße", types:["S"], lines:["S1","S25","S26"] },
  { name: "Frankfurter Allee", types:["S","U"], lines:["S41","S42","U5"] },
  { name: "Frankfurter Tor", types:["U"], lines:["U5"] },
  { name: "Franz-Neumann-Platz (Am Schäfersee) (FN)", types:["U"], lines:["U8"] },
  { name: "Freie Universität (Thielplatz)", types:["U"], lines:["U3"] },
  { name: "Friedenau", types:["S"], lines:["S1"] },
  { name: "Friedrichsfelde Ost", types:["S"], lines:["S5","S7","S75"] },
  { name: "Friedrichsfelde", types:["U"], lines:["U5"] },
  { name: "Friedrichshagen", types:["S"], lines:["S3"] },
  { name: "Friedrichstraße", types:["S","U","R"], lines:["S1","S2","S3","S5","S7","S9","U6"] },
  { name: "Friedrich-Wilhelm-Platz", types:["U"], lines:["U9"] },
  { name: "Frohnau", types:["S"], lines:["S1"] },
  { name: "Gehrenseestraße", types:["S"], lines:["S75"] },
  { name: "Gesundbrunnen", types:["S","U","R"], lines:["S1","S2","S25","S26","S41","S42","U8"] },
  { name: "Gleisdreieck", types:["U"], lines:["U1","U2","U3"] },
  { name: "Gneisenaustraße", types:["U"], lines:["U7"] },
  { name: "Görlitzer Bahnhof", types:["U"], lines:["U1","U3"] },
  { name: "Greifswalder Straße", types:["S"], lines:["S8","S85","S41","S42"] },
  { name: "Grenzallee", types:["U"], lines:["U7"] },
  { name: "Grünau", types:["S"], lines:["S8","S85","S9","S45","S46"] },
  { name: "Grünbergallee", types:["S"], lines:["S9"] },
  { name: "Grunewald", types:["S","R"], lines:["S3","S5","S7","S9"] },
  { name: "Güntzelstraße", types:["U"], lines:["U9"] },
  { name: "Hackescher Markt", types:["S"], lines:["S3","S5","S7","S9"] },
  { name: "Halemweg", types:["U"], lines:["U7"] },
  { name: "Halensee", types:["S"], lines:["S41","S42","S46"] },
  { name: "Hallesches Tor", types:["U"], lines:["U1","U3","U6"] },
  { name: "Hansaplatz", types:["U"], lines:["U9"] },
  { name: "Haselhorst", types:["U"], lines:["U7"] },
  { name: "Hauptbahnhof", types:["S","U","R"], lines:["S3","S5","S7","S9","U5"] },
  { name: "Hausvogteiplatz", types:["U"], lines:["U2"] },
  { name: "Heerstraße", types:["S","R"], lines:["S3","S9"] },
  { name: "Heidelberger Platz", types:["S","U"], lines:["S41","S42","S46","U3"] },
  { name: "Heiligensee", types:["S"], lines:["S25"] },
  { name: "Heinrich-Heine-Straße", types:["U"], lines:["U8"] },
  { name: "Hellersdorf", types:["U"], lines:["U5"] },
  { name: "Hermannplatz", types:["U"], lines:["U7","U8"] },
  { name: "Hermannstraße", types:["S","U"], lines:["S41","S42","S45","S46","S47","U8"] },
  { name: "Hermsdorf", types:["S"], lines:["S1"] },
  { name: "Hirschgarten", types:["S"], lines:["S3"] },
  { name: "Hohenschönhausen", types:["S"], lines:["S75"] },
  { name: "Hohenzollerndamm", types:["S"], lines:["S41","S42","S46"] },
  { name: "Hohenzollernplatz", types:["U"], lines:["U3"] },
  { name: "Holzhauser Straße", types:["U"], lines:["U6"] },
  { name: "Hönow", types:["U"], lines:["U5"] },
  { name: "Humboldthain", types:["S"], lines:["S1","S2","S25","S26"] },
  { name: "Innsbrucker Platz", types:["S","U"], lines:["S41","S42","S46","U4"] },
  { name: "Jakob-Kaiser-Platz", types:["U"], lines:["U7"] },
  { name: "Jannowitzbrücke", types:["S","U"], lines:["S3","S5","S7","S9","U8"] },
  { name: "Johannisthal", types:["S"], lines:["S45","S46"] },
  { name: "Johannisthaler Chaussee (Gropiusstadt)", types:["U"], lines:["U7"] },
  { name: "Julius-Leber-Brücke", types:["S"], lines:["S1"] },
  { name: "Jungfernheide", types:["S","U","R"], lines:["S41","S42","S46","U7"] },
  { name: "Kaiserdamm", types:["U"], lines:["U2"] },
  { name: "Kaiserin-Augusta-Straße", types:["U"], lines:["U6"] },
  { name: "Karl-Bonhoeffer-Nervenklinik", types:["S","U"], lines:["S25","U8"] },
  { name: "Karl-Marx-Straße", types:["U"], lines:["U7"] },
  { name: "Karlshorst", types:["S","R"], lines:["S3"] },
  { name: "Karow", types:["S","R"], lines:["S2"] },
  { name: "Kaulsdorf", types:["S"], lines:["S5"] },
  { name: "Kaulsdorf-Nord", types:["U"], lines:["U5"] },
  { name: "Kienberg (Gärten der Welt)", types:["U"], lines:["U5"] },
  { name: "Kleistpark", types:["U"], lines:["U7"] },
  { name: "Klosterstraße", types:["U"], lines:["U2"] },
  { name: "Kochstraße (Checkpoint Charlie)", types:["U"], lines:["U6"] },
  { name: "Köllnische Heide", types:["S"], lines:["S45","S46","S47"] },
  { name: "Konstanzer Straße", types:["U"], lines:["U7"] },
  { name: "Köpenick", types:["S","R"], lines:["S3"] },
  { name: "Kottbusser Tor", types:["U"], lines:["U1","U3","U8"] },
  { name: "Krumme Lanke", types:["U"], lines:["U3"] },
  { name: "Kurfürstendamm", types:["U"], lines:["U1","U9"] },
  { name: "Kurfürstenstraße", types:["U"], lines:["U1"] },
  { name: "Kurt-Schumacher-Platz", types:["U"], lines:["U6"] },
  { name: "Landsberger Allee", types:["S"], lines:["S8","S85","S41","S42"] },
  { name: "Lankwitz", types:["S"], lines:["S25"] },
  { name: "Leinestraße", types:["U"], lines:["U8"] },
  { name: "Leopoldplatz", types:["U"], lines:["U6","U9"] },
  { name: "Lichtenberg", types:["S","U","R"], lines:["S5","S7","S75","U5"] },
  { name: "Lichtenrade", types:["S"], lines:["S2"] },
  { name: "Lichterfelde Ost", types:["S","R"], lines:["S25","S26"] },
  { name: "Lichterfelde Süd", types:["S"], lines:["S25","S26"] },
  { name: "Lichterfelde West", types:["S"], lines:["S1"] },
  { name: "Lindauer Allee", types:["U"], lines:["U8"] },
  { name: "Lipschitzallee", types:["U"], lines:["U7"] },
  { name: "Louis-Lewin-Straße", types:["U"], lines:["U5"] },
  { name: "Magdalenenstraße", types:["U"], lines:["U5"] },
  { name: "Mahlsdorf", types:["S","R"], lines:["S5"] },
  { name: "Marienfelde", types:["S"], lines:["S2"] },
  { name: "Märkisches Museum", types:["U"], lines:["U2"] },
  { name: "Marzahn", types:["S"], lines:["S7"] },
  { name: "Mehringdamm", types:["U"], lines:["U6","U7"] },
  { name: "Mehrower Allee", types:["S"], lines:["S7"] },
  { name: "Mendelssohn-Bartholdy-Park", types:["U"], lines:["U2"] },
  { name: "Messe Nord/ICC", types:["S"], lines:["S41","S42","S46"] },
  { name: "Messe Süd", types:["S"], lines:["S3","S9"] },
  { name: "Mexikoplatz", types:["S"], lines:["S1"] },
  { name: "Mierendorffplatz", types:["U"], lines:["U7"] },
  { name: "Möckernbrücke", types:["U"], lines:["U1","U3","U7"] },
  { name: "Mohrenstraße", types:["U"], lines:["U2"] },
  { name: "Moritzplatz", types:["U"], lines:["U8"] },
  { name: "Museumsinsel", types:["U"], lines:["U5"] },
  { name: "Naturkundemuseum", types:["U"], lines:["U6"] },
  { name: "Nauener Platz", types:["U"], lines:["U9"] },
  { name: "Neukölln", types:["S","U"], lines:["S41","S42","S45","S46","S47","U7"] },
  { name: "Neu-Westend", types:["U"], lines:["U2"] },
  { name: "Nikolassee", types:["S"], lines:["S1","S7"] },
  { name: "Nollendorfplatz", types:["U"], lines:["U1","U2","U3","U4"] },
  { name: "Nordbahnhof", types:["S"], lines:["S1","S2","S25","S26"] },
  { name: "Nürnberger Platz", types:["U"], lines:["U3"] },
  { name: "Oberspree", types:["S"], lines:["S47"] },
  { name: "Olympiastadion", types:["S"], lines:["S3","S9"] },
  { name: "Onkel Toms Hütte", types:["U"], lines:["U3"] },
  { name: "Oranienburger Straße", types:["S"], lines:["S1","S2","S25","S26"] },
  { name: "Oranienburger Tor", types:["U"], lines:["U6"] },
  { name: "Osdorfer Straße", types:["S"], lines:["S25","S26"] },
  { name: "Oskar-Helene-Heim", types:["U"], lines:["U3"] },
  { name: "Osloer Straße", types:["U"], lines:["U8","U9"] },
  { name: "Ostbahnhof", types:["S","R"], lines:["S3","S5","S7","S9"] },
  { name: "Ostkreuz", types:["S","R"], lines:["S3","S41","S42","S8","S85"] },
  { name: "Otisstraße", types:["U"], lines:["U6"] },
  { name: "Pankow", types:["S","U"], lines:["S2","S8","S85","U2"] },
  { name: "Pankow-Heinersdorf", types:["S"], lines:["S2","S8","S85"] },
  { name: "Pankstraße", types:["U"], lines:["U8"] },
  { name: "Paracelsus-Bad", types:["U"], lines:["U8"] },
  { name: "Paradestraße", types:["U"], lines:["U6"] },
  { name: "Parchimer Allee", types:["U"], lines:["U7"] },
  { name: "Paulsternstraße", types:["U"], lines:["U7"] },
  { name: "Pichelsberg", types:["S"], lines:["S3","S9"] },
  { name: "Plänterwald", types:["S"], lines:["S8","S85","S9"] },
  { name: "Platz der Luftbrücke", types:["U"], lines:["U6"] },
  { name: "Podbielskiallee", types:["U"], lines:["U3"] },
  { name: "Poelchaustraße", types:["U"], lines:["U5"] },
  { name: "Potsdamer Platz", types:["S","U","R"], lines:["S1","S2","S25","S26","U2"] },
  { name: "Prenzlauer Allee", types:["S"], lines:["S8","S85","S41","S42"] },
  { name: "Priesterweg", types:["S"], lines:["S2","S25","S26"] },
  { name: "Prinzenstraße", types:["U"], lines:["U1","U3"] },
  { name: "Rahnsdorf", types:["S"], lines:["S3"] },
  { name: "Raoul-Wallenberg-Straße", types:["S"], lines:["S7"] },
  { name: "Rathaus Neukölln", types:["U"], lines:["U7"] },
  { name: "Rathaus Reinickendorf", types:["U"], lines:["U8"] },
  { name: "Rathaus Schöneberg", types:["U"], lines:["U4"] },
  { name: "Rathaus Steglitz", types:["U"], lines:["U9"] },
  { name: "Rehberge", types:["U"], lines:["U6"] },
  { name: "Reinickendorfer Straße", types:["U"], lines:["U6"] },
  { name: "Residenzstraße", types:["U"], lines:["U8"] },
  { name: "Richard-Wagner-Platz", types:["U"], lines:["U7"] },
  { name: "Rohrdamm", types:["U"], lines:["U7"] },
  { name: "Rosa-Luxemburg-Platz", types:["U"], lines:["U2"] },
  { name: "Rosenthaler Platz", types:["U"], lines:["U8"] },
  { name: "Rotes Rathaus", types:["U"], lines:["U5"] },
  { name: "Rüdesheimer Platz", types:["U"], lines:["U3"] },
  { name: "Rudow", types:["U"], lines:["U7"] },
  { name: "Ruhleben", types:["U"], lines:["U2"] },
  { name: "Rummelsburg", types:["S"], lines:["S3"] },
  { name: "Samariterstraße", types:["U"], lines:["U5"] },
  { name: "Savignyplatz", types:["S"], lines:["S3","S5","S7","S9"] },
  { name: "Scharnweberstraße", types:["U"], lines:["U6"] },
  { name: "Schichauweg", types:["S"], lines:["S2"] },
  { name: "Schillingstraße", types:["U"], lines:["U5"] },
  { name: "Schlachtensee", types:["S"], lines:["S1"] },
  { name: "Schlesisches Tor", types:["U"], lines:["U1","U3"] },
  { name: "Schloßstraße", types:["U"], lines:["U9"] },
  { name: "Schöneberg", types:["S"], lines:["S1"] },
  { name: "Schöneweide", types:["S","R"], lines:["S45","S46","S47","S8","S85","S9"] },
  { name: "Schönhauser Allee", types:["S","U"], lines:["S8","S85","S41","S42","U2"] },
  { name: "Schönholz", types:["S"], lines:["S1","S25","S26"] },
  { name: "Schönleinstraße", types:["U"], lines:["U8"] },
  { name: "Schulzendorf", types:["S"], lines:["S85"] },
  { name: "Schwartzkopffstraße", types:["U"], lines:["U6"] },
  { name: "Seestraße", types:["U"], lines:["U6"] },
  { name: "Senefelderplatz", types:["U"], lines:["U2"] },
  { name: "Siemensdamm", types:["U"], lines:["U7"] },
  { name: "Sonnenallee", types:["S"], lines:["S41","S42"] },
  { name: "Sophie-Charlotte-Platz", types:["U"], lines:["U2"] },
  { name: "Spandau / Rathaus Spandau", types:["S","U","R"], lines:["S3","S9","U7"] },
  { name: "Spichernstraße", types:["U"], lines:["U3","U9"] },
  { name: "Spindlersfeld", types:["S"], lines:["S47"] },
  { name: "Spittelmarkt", types:["U"], lines:["U2"] },
  { name: "Springpfuhl", types:["S"], lines:["S7","S75"] },
  { name: "Staaken", types:["R"], lines:[] },
  { name: "Stadtmitte", types:["U"], lines:["U2","U6"] },
  { name: "Storkower Straße", types:["S"], lines:["S41","S42"] },
  { name: "Strausberger Platz", types:["U"], lines:["U5"] },
  { name: "Stresow", types:["S"], lines:["S3","S9"] },
  { name: "Südende", types:["S"], lines:["S25","S26"] },
  { name: "Südkreuz", types:["S","R"], lines:["S2","S25","S26"] },
  { name: "Südstern", types:["U"], lines:["U7"] },
  { name: "Sundgauer Straße", types:["S"], lines:["S1"] },
  { name: "Tegel", types:["S"], lines:["S25"] },
  { name: "Tempelhof", types:["S","U"], lines:["S41","S42","S45","S46","U6"] },
  { name: "Theodor-Heuss-Platz", types:["U"], lines:["U2"] },
  { name: "Tiergarten", types:["S"], lines:["S3","S5","S7","S9"] },
  { name: "Tierpark", types:["U"], lines:["U5"] },
  { name: "Treptower Park", types:["S"], lines:["S8","S85","S9","S41","S42"] },
  { name: "Turmstraße", types:["U"], lines:["U9"] },
  { name: "Uhlandstraße", types:["U"], lines:["U1"] },
  { name: "Ullsteinstraße", types:["U"], lines:["U6"] },
  { name: "Unter den Linden", types:["U"], lines:["U5","U6"] },
  { name: "Viktoria-Luise-Platz", types:["U"], lines:["U4"] },
  { name: "Vinetastraße", types:["U"], lines:["U2"] },
  { name: "Voltastraße", types:["U"], lines:["U8"] },
  { name: "Waidmannslust", types:["S"], lines:["S1"] },
  { name: "Walther-Schreiber-Platz", types:["U"], lines:["U9"] },
  { name: "Wannsee", types:["S","R"], lines:["S1","S7"] },
  { name: "Warschauer Straße", types:["S","U"], lines:["S3","S5","S7","S9","U1","U3"] },
  { name: "Wartenberg", types:["S"], lines:["S75"] },
  { name: "Weberwiese", types:["U"], lines:["U5"] },
  { name: "Wedding", types:["S","U"], lines:["S41","S42","U6"] },
  { name: "Weinmeisterstraße", types:["U"], lines:["U8"] },
  { name: "Westend", types:["S"], lines:["S41","S42","S46"] },
  { name: "Westhafen", types:["S","U"], lines:["S41","S42","U9"] },
  { name: "Westkreuz", types:["S"], lines:["S3","S41","S42","S46","S5","S7","S9"] },
  { name: "Westphalweg", types:["U"], lines:["U6"] },
  { name: "Wilhelmshagen", types:["S"], lines:["S3"] },
  { name: "Wilhelmsruh", types:["S"], lines:["S1","S85"] },
  { name: "Wilmersdorfer Straße", types:["U"], lines:["U7"] },
  { name: "Wittenau", types:["S","U"], lines:["S1","U8"] },
  { name: "Wittenbergplatz", types:["U"], lines:["U1","U2","U3"] },
  { name: "Wollankstraße", types:["S"], lines:["S1","S25","S26"] },
  { name: "Wuhletal", types:["S","U"], lines:["S5","U5"] },
  { name: "Wuhlheide", types:["S"], lines:["S3"] },
  { name: "Wutzkyallee", types:["U"], lines:["U7"] },
  { name: "Yorckstraße", types:["S","U"], lines:["S1","S2","S25","S26","U7"] },
  { name: "Zehlendorf", types:["S"], lines:["S1"] },
  { name: "Zitadelle", types:["U"], lines:["U7"] },
  { name: "Zoologischer Garten", types:["S","U","R"], lines:["S3","S5","S7","S9","U2","U9"] },
  { name: "Zwickauer Damm", types:["U"], lines:["U7"] },
];

export const seedStations = SEED_STATIONS;
